#
# GitHub-Actions CI
#
# This workflow runs tests for the github-actions implemented in `./action/`.
# It verifies accessibility of the released artifacts and functionality of the
# latest version.
#

name: "Custom Action Tests"

on:
  pull_request:
  push:
    branches-ignore: ["pr/**"]
    tags: ["**"]
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  msdevshell_testing:
    name: "Test the MsDevShell Action"

    strategy:
      matrix:
        arch: ["x64", "x86"]
        os: ["windows-2022", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v3

    - name: "Run local MsDevShell action"
      uses: ./action/msdevshell
      with:
        architecture: ${{ matrix.arch }}

    - name: "Verify MsDevShell"
      run: cl

  msdevshell_release:
    name: "Verify the MsDevShell Action Release"
    runs-on: "windows-latest"

    steps:
    - name: "Run released MsDevShell action"
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: "x64"

    - name: "Verify MsDevShell"
      run: cl
