#
# Linter Checks
#
# This workflow runs code linters on the entire code-base. Different kind of
# linters for different sources are available.
#

name: "Linter Checks"

on:
  pull_request:
  push:
    branches-ignore: ["pr/**"]
    tags: ["**"]
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  shellcheck:
    name: "Differential ShellCheck"

    permissions:
      contents: read
      pull-requests: write
      security-events: write

    runs-on: "ubuntu-latest"

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Run the Differential ShellCheck"
      uses: redhat-plumbers-in-action/differential-shellcheck@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
